Takanon common knowledge
whiletrue-industries/rebuilding-bots pull request #3
Opened 2024-12-24 20:48 UTC by noamoss

2024-12-24 20:51 UTC, noamoss commented
closes https://github.com/whiletrue-industries/botnim/issues/3

2025-01-05 22:19 UTC, akariv requested changes

2025-01-05 22:19 UTC, akariv commented on botnim/sync.py
> +logging.basicConfig(level=logging.INFO)
better to be in config and not here.

2025-01-05 22:19 UTC, akariv commented on botnim/sync.py
> +        # Find the main context and common knowledge context
I think this logic is very complex and very specific (e.g. assuming there are only two kinds of 'knowledge bases').
I get that the limitation in the OpenAI system is forcing us to do this, but for the elasticsearch solution this won't be required again.

So I suggest we don't merge this specific PR and instead upgrade it to write the different knowledge bases to separate ES indexes.

As a general note, this function became a monstrosity... we will be better off with a more modular design moving forward.

2025-01-09 07:01 UTC, noamoss commented on botnim/sync.py
> +logging.basicConfig(level=logging.INFO)
fixed

2025-01-09 10:14 UTC, closed without merging